#=============================================================================
# Copyright Luiz Carlos Faria 2022. All Rights Reserved.
# This file is licensed under the MIT License.
# License text available at https://opensource.org/licenses/MIT
#=============================================================================

---
apiVersion: v1
kind: Namespace
metadata:
  name: eshop-resources

---
apiVersion: v1
kind: Namespace
metadata:
  name: eshop-services
