apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  creationTimestamp: null
  name: eshop
  namespace: eshop-resources
scheduler:
  name: ""
spec:
  certConfig: {}
  credsSecret:
    name: eshop-creds-secret
  image: minio/minio:RELEASE.2022-05-23T18-45-11Z
  imagePullSecret: {}
  mountPath: /export
  pools:
  - affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: v1.min.io/tenant
              operator: In
              values:
              - eshop
          topologyKey: kubernetes.io/hostname
    resources: {}
    servers: 2
    volumeClaimTemplate:
      apiVersion: v1
      kind: persistentvolumeclaims
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 2T
      status: {}
    volumesPerServer: 2
  requestAutoCert: true
  users:
  - name: eshop-user-1
status:
  availableReplicas: 0
  certificates: {}
  currentState: ""
  pools: null
  revision: 0
  syncVersion: ""
  usage: {}

---
apiVersion: v1
data:
  accesskey: YjFkMTUxZDMtODg0OC00ZjMzLTlhNjItOGI3ZDVjMDgyNGU3
  secretkey: YjVkNzg3NTMtYjVhNC00NzcxLWJlYWYtYzMxY2EyOGI0YmZm
kind: Secret
metadata:
  creationTimestamp: null
  name: eshop-creds-secret
  namespace: eshop-resources

---
apiVersion: v1
data:
  CONSOLE_ACCESS_KEY: YWRtaW4=
  CONSOLE_SECRET_KEY: N2JhNGZlZDgtNmNkYy00NzA3LWI0OGMtZmE0Njg0YjhjNzM2
kind: Secret
metadata:
  creationTimestamp: null
  name: eshop-user-1
  namespace: eshop-resources


---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: gago-minio-ingress
  namespace: minio-operator
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: "minio-188-40-114-31.nip.io"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: console
                port:
                  number: 9090
