#=============================================================================
# Copyright Luiz Carlos Faria 2022. All Rights Reserved.
# This file is licensed under the MIT License.
# License text available at https://opensource.org/licenses/MIT
#=============================================================================

---
kind: Secret
apiVersion: v1
metadata:
  name: rabbitmq-secret--admin
  namespace: eshop-resources
type: kubernetes.io/basic-auth
stringData:
  username: eshop_admin
  password: eshop_pass


---
kind: User
apiVersion: rabbitmq.com/v1beta1
metadata:
  name: rabbitmq-user--admin
  namespace: eshop-resources
spec:
  rabbitmqClusterReference:
    name: rabbitmq
  tags:
  - administrator
  importCredentialsSecret:
    name: rabbitmq-secret--admin

---
kind: Permission
apiVersion: rabbitmq.com/v1beta1
metadata:
  name: rabbitmq-permission--admin1
  namespace: eshop-resources
spec:
  vhost: "eshop"
  user: "eshop_admin"
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitmq

---
kind: Permission
apiVersion: rabbitmq.com/v1beta1
metadata:
  name: rabbitmq-permission--admin2
  namespace: eshop-resources
spec:
  vhost: "log"
  user: "eshop_admin"
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitmq

---
kind: Permission
apiVersion: rabbitmq.com/v1beta1
metadata:
  name: rabbitmq-permission--admin3
  namespace: eshop-resources
spec:
  vhost: "/"
  user: "eshop_admin"
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitmq    
