#=============================================================================
# Copyright Luiz Carlos Faria 2022. All Rights Reserved.
# This file is licensed under the MIT License.
# License text available at https://opensource.org/licenses/MIT
#=============================================================================

---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: app-secret
  namespace: eshop-resources
data:
## username: eshop
## password: J9Of0497BM@c$Bs
  username: ZXNob3A=
  password: SjlPZjA0OTdCTUBjJEJz


---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: kong-secret
  namespace: eshop-resources
data:
## username: konguser
## password: qAix6zjWBLpZ%6Tk&B0u
  username: a29uZ3VzZXI=
  password: cUFpeDZ6aldCTHBaJTZUayZCMHU=


---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: superuser-secret
  namespace: eshop-resources
data:
## username: postgres
## password: postgresJ9Of0497BM@c$Bs
  username: cG9zdGdyZXM=
  password: cG9zdGdyZXNKOU9mMDQ5N0JNQGMkQnM=



---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: eshop-postgres-cluster
  namespace: eshop-resources
spec:
  instances: 3
  superuserSecret:
    name: superuser-secret
  bootstrap:
    initdb:
      database: eshop
      owner: eshop
      encoding: "UTF8"
      postInitSQL:
        - CREATE DATABASE kong  WITH OWNER = eshop ENCODING = 'UTF8' CONNECTION LIMIT = -1;
        - CREATE ROLE kong_user WITH LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT NOREPLICATION CONNECTION LIMIT -1 PASSWORD 'qAix6zjWBLpZ%6Tk&B0u';
        - GRANT ALL ON DATABASE kong TO kong_user;
      secret:
        name: app-secret
  storage:
    storageClass: local-path
    size: 4Gi
