#=============================================================================
# Copyright Luiz Carlos Faria 2022. All Rights Reserved.
# This file is licensed under the MIT License.
# License text available at https://opensource.org/licenses/MIT
#=============================================================================

---
kind: RabbitmqCluster
apiVersion: rabbitmq.com/v1beta1
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
  namespace: eshop-resources
spec:
  replicas: 3
  image: rabbitmq:3.10.5-management
  service:
    type: ClusterIP
  persistence:
    storageClassName: longhorn
    storage: 10Gi
  resources:
    requests:
      cpu: 4
      memory: 10Gi
    limits:
      cpu: 4
      memory: 10Gi
  rabbitmq:
    additionalConfig: |
      cluster_partition_handling = pause_minority
      vm_memory_high_watermark_paging_ratio = 0.99
      disk_free_limit.relative = 1.0
      collect_statistics = fine
      collect_statistics_interval = 1000

---
# kind: Ingress
# apiVersion: networking.k8s.io/v1
# metadata:
#   name: rabbitmq-ingress
#   namespace: eshop-resources
# spec:
#   rules:
#     - host: "rabbitmq-188-40-114-31.nip.io"
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: rabbitmq
#                 port:
#                   number: 15672
---
kind: Service
apiVersion: v1
metadata:
  name: rabbitmq-nodeport
  namespace: eshop-resources
  labels:
    app: rabbitmq
spec:
  ports:
    - name: amqp
      protocol: TCP
      appProtocol: amqp
      port: 5672
      targetPort: 5672
      nodePort: 30780
    - name: management
      protocol: TCP
      appProtocol: http
      port: 15672
      targetPort: 15672
      nodePort: 30779
  selector:
    app.kubernetes.io/name: rabbitmq
  type: NodePort
