#=============================================================================
# Copyright Luiz Carlos Faria 2022. All Rights Reserved.
# This file is licensed under the MIT License.
# License text available at https://opensource.org/licenses/MIT
#=============================================================================

---
kind: RabbitmqCluster
apiVersion: rabbitmq.com/v1beta1
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
  namespace: eshop-resources
spec:
  replicas: 3
  image: rabbitmq:3.10.5-management
  service:
    type: ClusterIP
  persistence:
    storageClassName: local-path
    storage: 10Gi
  resources:
    requests:
      cpu: 4
      memory: 10Gi
    limits:
      cpu: 4
      memory: 10Gi
  rabbitmq:
    additionalConfig: |
      cluster_partition_handling = pause_minority
      vm_memory_high_watermark_paging_ratio = 0.99
      disk_free_limit.relative = 1.0
      collect_statistics = fine
      collect_statistics_interval = 1000


---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: rabbitmq-ingress
  namespace: eshop-resources
  #annotations:
    #ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: "rabbitmq-188-40-114-31.nip.io"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rabbitmq
                port:
                  number: 15672
