#=============================================================================
# Copyright Luiz Carlos Faria 2022. All Rights Reserved.
# This file is licensed under the MIT License.
# License text available at https://opensource.org/licenses/MIT
#=============================================================================

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: krakend-config
  namespace: eshop-resources
data:
  krakend.json: |
    {
        "$schema": "https://www.krakend.io/schema/v3.json",
        "version": 3,
        "extra_config": {
            "telemetry/logging": {
                "level": "DEBUG",
                "prefix": "[KRAKEND]",
                "syslog": false,
                "stdout": true,
                "format": "logstash"
            },
            "telemetry/logstash": {
                "enabled": false
            }
        },
        "timeout": "3000ms",
        "cache_ttl": "300s",
        "output_encoding": "json",
        "name": "krakend01",
        "port": 8080,
        "endpoints": [
            {
                "endpoint": "/http-log/{route}",
                "method": "POST",
                "output_encoding": "json",
                "extra_config": {},
                "backend": [
                    {
                        "url_pattern": "/",
                        "encoding": "json",
                        "method": "POST",
                        "extra_config": {
                            "backend/amqp/producer": {
                                "name": "krakend-log-exchange",
                                "exchange": "krakend-log-queue",
                                "durable": true,
                                "delete": false,
                                "no_wait": true,
                                "no_local": false,
                                "mandatory": false,
                                "routing_key": "Route"
                            }
                        },
                        "host": [
                            "amqp://log_user:log_pass@rabbitmq.svc:5672/log"
                        ],
                        "disable_host_sanitize": true
                    }
                ]
            }
        ]
    }



---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: krakend
  name: krakend
  namespace: eshop-resources
spec:
  replicas: 1
  selector:
    matchLabels:
      app: krakend
  template:
    metadata:
      labels:
        app: krakend
    spec:
      containers:
        - name: krakend
          args:
            - run
            - --config
            - /etc/krakend/krakend.json
          image: devopsfaith/krakend:2.0.1
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - name: krakend-config
              mountPath: /etc/krakend/krakend.json
              subPath: krakend.json
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: krakend-config
          configMap:
            name: krakend-config


---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: krakend
  name: krakend-service
  namespace: eshop-resources
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: krakend
  type: ClusterIP
status:
  loadBalancer: {}